
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BMP001', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17056', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3863', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3863', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3863', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3863', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3863', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6062', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6062', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6062', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6062', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6062', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020MRT', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020MRT', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020MRT', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020MRT', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 17020MRT', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18009', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18009', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18009', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18009', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18009', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18009', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18010', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18010', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18010', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18010', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18010', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18010', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18011', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18011', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18011', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18011', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18011', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18011', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 18011', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5558R', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8265', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8265', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8265', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8265', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8265', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8265', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8595', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8595', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8596', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8596', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8596', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8596', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8596', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8599', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8599', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8599', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 8599', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9028M', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9101', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9101', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9101', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9101', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9101', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9101', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 4143', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 4143', 'dorado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 4143', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 4143', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 4143', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 4143', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 4143', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 040', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 040', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 040', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 266', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 266', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 342', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 342', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 535', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 535', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7301', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7553', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7554', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7554', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7554', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7554', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7554', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7554', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7555', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 7555', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8266', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8266', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8266', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8266', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8591', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8591', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8591', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8591', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8591', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8592', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8592', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8592', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8592', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8592', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8593', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8593', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8593', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8593', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8600', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8600', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 930', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5555', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5555', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5555', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5555', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5555', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 5555', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 7660', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 7660', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 7660', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 7660', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 7660', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('AL 9029', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17111A', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17111A', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17111A', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17111A', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17111A', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17111A', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17111A', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2173 ', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2173 ', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2173 ', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2173 ', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2173 ', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2311', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2311', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2311', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2311', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 2311', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 5025', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 5025', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 5025', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 5143B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 5143B', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 5143B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 5143B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 5143B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6063', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6063', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6063', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6063', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6063', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 6063', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7019', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7019', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7019', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7019', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7019', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7019', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7019', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7104C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7104C', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7104C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7104C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7104C', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7104C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7104C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7113', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7113', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7113', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7113', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7113', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7113', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7113', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7113', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7332', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7332', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7332', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7332', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7332', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7332', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7332', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7713B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7713B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7713B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7713B', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7713B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8030', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8030', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8030', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8030', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8030', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8030', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8204', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8204', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8204', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8204', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8204', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8204', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8324C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8324C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8324C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8324C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8503B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8503B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8503B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8503B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 6024', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8260', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM 8260', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM708', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM708', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM708', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('FM708', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 046', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 046', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 046', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17063', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17063', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17063', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17063', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17063', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17063', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17063', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17122', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17122', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17122', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17122', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17122', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 17122', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3536B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3536B', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3536B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3536B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3536B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3536B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3902C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3902C', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3902C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3902C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3902C', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 3902C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7009C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7009C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7009C', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7009C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 7009C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8191', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8191', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8191', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8191', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8191', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8191', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8191', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8232C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8232C', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8232C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8232C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8232C', 'rosa ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8232C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8384', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8384', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8384', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8384', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8384', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8384', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8384', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8384', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8405T', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8412B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8412B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8412B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8412B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8412B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8423', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8423', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8423', 'naranaja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8423', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8423', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8423', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594B', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594B', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594B', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594C', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8594C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8597', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8597', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8597', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8597', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8597', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8597', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8598', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8598', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8598', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8598', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8598', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8598', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1001', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1001', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1001', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1001', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1001', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1001', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1112', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1112', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1112', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-1112', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2001C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2001C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2001C', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2001C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2001C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007C', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2007C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013B', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2013B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2040', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2040', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2040', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2040', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2040', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173A', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173A', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173A', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173A', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173A', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173A', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173B', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173B', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173B', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2173C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2185A', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2185A', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2185A', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2185A', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2185A', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2185A', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197A', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197A', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197A', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197A', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197A', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197A', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197T', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197T', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197T', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197T', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2197T', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2214', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2214', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2214', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2214', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2214', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2214', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2214', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-235', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2365', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2365', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2365', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2365', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2365', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2805', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2809', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2911', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2911', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2911', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-2911', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30128', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30128', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30128', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30128', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30128', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30371', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30371', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30371', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30371', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-30371', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3157', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3157', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3157', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3157', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3157', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3570', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802C', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802D', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802D', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802D', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802D', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802D', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802D', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3802D', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3818C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3818C', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3818C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3818C', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3818C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3818C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3904B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3904B', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3904B', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3904B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3904B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3904B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3904B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3914', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3914', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3914', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3914', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3914', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3914', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-3914', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5208B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5208B', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5208B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5208B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5208B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5244C', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5244C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5244C', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5244C', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5244C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5244C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5244C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5244C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5501C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5501C', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5501C', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5501C', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5501C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5501C', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5501C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5501C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5589', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5589', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5589', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-5589', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-595C', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-595C', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-595C', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-595C', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-595C', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-595C', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6693 101', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6693 101', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6693 101', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6693 101', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6693 101', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6801', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6801', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6801', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6801', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6801', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-6801', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7435B', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7990', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7990', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7990', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-7990', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-925', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-925', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-925', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-925', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-925', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-925', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-925', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP-9902', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('C-01', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('GH-1527A', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('GH-1527A', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('GH-1527A', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('GH-1527A', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('GH-1527A', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BP 8271', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 01', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 010', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 011', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 012', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 013', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 013', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 014', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 015', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 016', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 017', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 017', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 017', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 017', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 018', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 018', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 018', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 018', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 019', ' azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 019', ' negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 019', ' plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 019', ' rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 02', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 020', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 021', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 022', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 03', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 04', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 04', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 04', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 05', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 06', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 07', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 07', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 07', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 08', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 08', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 08', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HR 09', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 01', ' blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 010', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 011', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 012', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 013', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 014', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 015', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 016', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 017', 'madera');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 018', 'madera');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 020', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 020', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 020', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 020', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 021', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 021', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 021', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 021', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 021', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 021', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 021', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 022', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 022', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 022', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 022', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 022', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 023', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 023', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 023', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 023', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 023', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 04', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 04', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 06', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 06', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 07', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 08', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 09', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LON 004', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LON 004', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LON 004', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LON 004', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LON 004', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LON 004', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 019', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 020', 'caoba');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 024', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 221', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 001', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 002', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 005', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 006', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 007', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 008', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 009', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 010', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 011', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 012', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 014', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 014', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 014', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 014', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 014', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 016', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 016', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 016', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 017', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 018', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 020', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 023', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 024', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 024', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 024', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 025', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 025', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 025', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 026', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 026', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 026', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 027', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 027', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('MK 027', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 001', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 001', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 001', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 001', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 002', ' azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 002', ' rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 002', ' verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 003', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 003', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 003', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 006', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 007', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 007', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('PK 007', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL 029', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL 029', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL 029', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CA 001', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CA 004', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CA 004', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CA 004', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CA 004', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CA 004', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CA 005', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 002', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 003', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 005', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 008', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 008', 'carton ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 008', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 008', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 008', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 018', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 019', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 020', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 020', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 020', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 020', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 021', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 022', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LEO 001', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 001', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 001', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 001', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 001', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LE 004', 'carton');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 003', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 003', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 003', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 003', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 003', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 003', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 003', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 006', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 006', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 006', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 006', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 006', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 006', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 006', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 006', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 007', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 007', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 007', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 007', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 007', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 007', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 008', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 008', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 009', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 010', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 010', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 012', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 013', 'cafe ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 014', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 015', 'plata ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 017', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 021', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 021', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 021', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 021', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 021', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 025', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 027', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 028', 'azul ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 028', 'naranja ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 028', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 028', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 028', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 028', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 029', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 030', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 031', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 031', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 031', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 031', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 031', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 032', 'azul ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 032', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 032', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 032', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 032', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 032', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 032', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 033', 'azul ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 033', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 033', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 033', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 033', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 033', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 034', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 034', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 034', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 034', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 034', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 034', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 034', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 035', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 035', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 036', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 037', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 037', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 037', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 037', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 037', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 040', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 040', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 040', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 040', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 040', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 041', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 041', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 041', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 041', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 041', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 042', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 043', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 044', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 045', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 045', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 045', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 045', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 045', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 046', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 046', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 046', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 046', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 046', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 048', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 049', 'beige');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 050', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 051', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 051', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 051', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 051', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 052', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 053', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 122', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 002', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 002', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 002', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 002', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 002', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 002', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 002', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 002', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 004', 'amarillo ');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 004', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 004', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 004', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 004', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 004', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 004', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 004', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 016', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('O 039', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 01', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 010', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 010', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 010', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 010', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 010', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 010', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 012', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 012', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 012', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 012', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 012', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 012', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 012', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 013', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 013', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 013', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 013', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 013', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 013', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 014', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 014', 'beige');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 014', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 014', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 014', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 014', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 014', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 014P', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 015C', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 016', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 016', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 017', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 017', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 017', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 018', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 019', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 019', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 019', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 019', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 020', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 021', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 021', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 021', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 021', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 022', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 023', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 024', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 025', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 025', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 026', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 027', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 028', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 028', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 028', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 04', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 04', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 04', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 05', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 05', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 05', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 05', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 06', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 06', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 06', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 06', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 07', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 07', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 07', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 07', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 07', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 07', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP 08', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('CP03', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP07', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP07', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP07', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP07', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP07', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP07', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP07', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP07', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP 08', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP 09', 'blanco/negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP 11', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP 12', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP 12', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('LP 12', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3551', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3551', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3551', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3551', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3551', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3551', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3551', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3973', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3973', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3973', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3973', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('3973', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('4070', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('4070', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('4070', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('4070', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('4070', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('4070', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 006', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 007', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 007', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 007', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 008', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 010', '');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 010', '');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 010', '');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 010', '');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 010', '');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 010', '');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 010', '');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 011', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 012', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 013', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 013', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 014', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 015', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 016', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 017', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 019', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 020', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 020', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 020', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 020', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 020', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 020', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 021', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 021', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 021', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 021', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 022', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 023', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 023', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 023', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 024', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 025', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 026', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 026', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 026', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 026', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 026', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 026', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 026', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 027', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 028', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 028', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 028', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 028', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 030', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 030', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 030', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 030', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 031', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 031', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 032', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 032', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 032', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 033', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 034', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 035', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 036', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 037', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 037', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 037', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 037', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 038', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 039', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 040', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 040', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 041', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 042', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 042', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 042', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 042', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 042', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 043', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 043', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 043', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 043', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 043', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 043', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 044', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 044', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 045', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 046', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 046', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 046', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 047', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 048', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('SO 049', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('HO 01', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 01', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 07', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 07', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 07', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 07', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 07', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 10', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 11', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 11', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 11', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 11', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 11', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 17', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 17', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 17', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 17', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 17', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 17', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 17', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 18', 'azul claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 18', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 18', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 18', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 18', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 18', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 18', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 18', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 19', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 19', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 19', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 19', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 19', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 19', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 19', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 19', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 20', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 20', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 20', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 20', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 20', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 21', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 21', 'beige');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 21', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 21', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 21', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 21', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 21', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 21', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 22', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 23', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 23', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 24', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T 25', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T26', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T26', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T26', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T26', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T26', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T27', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T27', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T27', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T28', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T29', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T29', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T29', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T29', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T29', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T29', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T29', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T29', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T30', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T31', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T31', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T32', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T32', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T34', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T34', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T35', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T36', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T36', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T36', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T36', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T37', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T37', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T38', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T38', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T38', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T38', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T38', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T39', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T39', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T40', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T41', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T42', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T43', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T44', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T44', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T44', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T44', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T45', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T45', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T45', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T45', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48T', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48T', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48T', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48T', 'transparente');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T48T', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T49', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T49', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T49', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T49', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T49', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T49', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T49', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T50', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T50', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T50', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T50', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T50', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T51', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T51', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T51', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T51', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T51', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T52', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T52', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T52', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T52', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T53', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T53', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T55', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T55', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T55', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T55', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T55', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T56', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T56', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T57', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T57', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T57', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T58', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T58', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T58', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T59', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T59', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T59', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T60', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T60', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T61', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T62', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T62', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T63', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T63', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T63', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T63', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T63', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T64', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T64', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T65', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T65', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T66', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T66', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T66', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T66', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T66', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T66', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T67', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T67', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T67', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T67', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T67', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T67', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T68', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T68', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T68', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T68', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T68', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T68', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T68', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T68', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T70', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T70', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T70', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T70', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T70', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T70', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T70', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T71', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T71', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T71', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T71', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T71', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('T71', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('TB500', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL001', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL001', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL001', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL001', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL001', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL001', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL001', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL002', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL002', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL002', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL002', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL002', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL002', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL002', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL004', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL005', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL005', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL005', 'morado');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL005', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL005', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL005', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL005', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL005', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL007', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL007', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL007', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL007', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL007', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL008', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL008', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL008', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL008', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL008', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL008', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL008', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL008', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL009', 'plata');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL010', 'amarillo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL010', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL010', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL010', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL010', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL010', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL010', 'verde claro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL011', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL011', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL011', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL011', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL012', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL012', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL012', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL013', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL015', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL015', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL015', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL015', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL015', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL016', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL016', 'blanco');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL016', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL016', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL016', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL017', 'cafe');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL017', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL018', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL019', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL020', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL020', 'gris');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL020', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL020', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL020', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL020', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL021', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL021', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL021', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL021', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL022', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL022', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL022', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL023', 'azul');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL023', 'naranja');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL023', 'negro');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL023', 'rojo');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL023', 'rosa');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL023', 'verde');
INSERT INTO `colores` (`modelo`, `color`) VALUES ('BL024', 'gris');
# 1423 records

